export default [
  {
    id: 1,
    title: "Sample Task 1",
    description: "Sample Task 1 Description",
    createdDate: "2020-01-01",
    type: "important",
    status: "pending",
    userId: 1,
  },
  {
    id: 2,
    title: "Sample Task 2",
    description: "Sample Task 2 Description",
    createdDate: "2020-01-01",
    type: "important",
    status: "completed",
    userId: 1,
  },
  {
    id: 3,
    title: "Sample Task 3",
    description: "Sample Task 3 Description",
    createdDate: "2020-01-01",
    type: "important",
    status: "pending",
    userId: 2,
  },
  {
    id: 4,
    title: "Sample Task 4",
    description: "Sample Task 4 Description",
    createdDate: "2020-01-01",
    type: "important",
    status: "completed",
    userId: 2,
  },
  {
    id: 5,
    title: "Sample Task 5",
    description: "Sample Task 5 Description",
    createdDate: "2020-01-01",
    type: "important",
    status: "new",
    userId: 3,
  },
  {
    id: 6,
    title: "Sample Task 6",
    description: "Sample Task 6 Description",
    createdDate: "2020-01-01",
    type: "important",
    status: "pending",
    userId: 3,
  },
];
